---
- name: ensure "kernel" with right permissions
  file: 
    path: /sys/kernel/mm/transparent_hugepage/enabled
    owner: root
    group: root
    state: file
    mode: 0755
    
- name: enable rules for transparent_hugepages for  always/never
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled
  
- name: ensure "kernel" with right permissions
  file: 
    path: /sys/kernel/mm/transparent_hugepage/defrag
    owner: root
    group: root
    state: file
    mode: 0755

- name: enable rules for transparent-hugepage-defrag  for  always/never
  shell: echo never > /sys/kernel/mm/transparent_hugepage/defrag

- name: Install rng-tools package
  yum:
    name: rng-tools
    state: latest

- name: Configure "/usr/lib/systemd/system/rngd.service" from current prod config
  template: 
    src: rngd.service
    dest: /usr/lib/systemd/system/rngd.service
  notify: restart rngd
