- name: Insert/Update system ctl
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      vm.overcommit_memory = 1
      net.ipv4.icmp_echo_ignore_broadcasts = 1
      fs.file-max = 1048576
      net.ipv4.tcp_syncookies = 1
      net.ipv6.conf.all.accept_ra = 0
      net.ipv4.conf.all.rp_filter = 1
      fs.suid_dumpable = 0
      net.ipv4.conf.all.send_redirects = 0
      net.ipv4.conf.default.accept_redirects = 0
      net.ipv4.conf.default.rp_filter = 1
      net.ipv6.conf.default.accept_redirects = 0
      net.ipv4.conf.default.accept_source_route = 0
      net.core.somaxconn = 65535
      net.ipv6.conf.all.accept_redirects = 0
      kernel.panic = 5
      net.ipv4.ip_forward = 0
      net.ipv4.conf.all.accept_source_route = 0
      net.ipv4.conf.default.send_redirects = 0
      net.ipv4.tcp_slow_start_after_idle = 0
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv4.conf.all.accept_redirects = 0
      net.ipv4.conf.all.secure_redirects = 0
      net.ipv4.tcp_max_syn_backlog = 4096
      kernel.randomize_va_space = 2
      net.ipv6.conf.default.accept_ra = 0
      net.ipv4.conf.default.secure_redirects = 0
      net.ipv4.icmp_ignore_bogus_error_responses = 1
      net.ipv4.conf.all.log_martians = 1
      net.ipv4.neigh.default.gc_thresh1 = 0
      net.ipv4.ip_local_port_range = 10001 65535
      kernel.shmmax = 17179869184
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv4.conf.default.log_martians = 1
      vm.swappiness = 1

