  - name: download latest stable redis
    yum: name=https://s3.amazonaws.com/runscope-packages/redis-3.2.10-2.el7.x86_64.rpm

  - name: create redis group
    group: name=redis state=present system=yes

  - name: create redis user
    user: name=redis group=redis createhome=yes home=/mnt/redis shell=/sbin/nologin state=present

  - name: ensure redis home directory exists
    file: path=/mnt/redis state=directory mode=0755 owner=redis group=redis

  - name: make sure that /mnt/redis/redis exists
    file: path=/mnt/redis/redis-{{ redis_port }} state=directory mode=0755 group=redis owner=redis

  - name: make sure redis.log file exists
    file: path=/var/log/redis/redis-{{ redis_port }}.log state=touch owner=redis group=redis mode=0644

  - name: Configure Redis server
    template: src=redis-6379.conf dest=/etc/
    notify: restart redis

  - name: Ensure redis pid file exists
    stat: path=/var/run/redis-{{ redis_port }}.pid
    register: pid_result

  - name: Fail if pid doesn't exists
    debug: msg=" redis pid file exists"
    when: pid_result.stat.exists

  - name: Start Redis
    service: name=redis state=started enabled=yes
  
  - name: wait for redis to start
    wait_for: port={{ redis_port }}

