#! /bin/sh
### BEGIN INIT INFO
# Provides:          urandom
# chkconfig:         2345 13 99
# Required-Start:    $remote_fs $network $named
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Seeds the /dev/urandom pseudo-random number generator
# Description:       Seed the pseudo-RNG in /dev/urandom with a unique seed
#                    from random.org. This script is a modification of
#                    Ubuntu's stock /etc/init.d/urandom and is necessary when
#                    launching multiple virtual machines from the same image.
#                    Without an external seed, those virtual machines would
#                    share a single seed.
# X-Author:          Ryan Park <ryan@ryanpark.org>
# X-Version:         1.0.1
### END INIT INFO

[ -c /dev/urandom ] || exit 0

PATH=/sbin:/usr/sbin:/bin:/usr/bin
POOLSIZE=512
[ -f /proc/sys/kernel/random/poolsize ] && POOLSIZE="$(cat /proc/sys/kernel/random/poolsize)"

# Source function library.
. /etc/init.d/functions

case "$1" in
  start|restart)
    echo -n $"Initializing random number generator: "
    TEMPFILE=`mktemp /tmp/urandom.$$.XXXXXX`
    curl -Ss -o "$TEMPFILE" "https://www.random.org/cgi-bin/randbyte?nbytes=$POOLSIZE&format=f"
    ES=$?
    if [ "$ES" -ne 0 ]; then
        echo_failure
        echo ""
        exit $ES
    fi
    FILESIZE=$(stat -c%s "$TEMPFILE")
    if [ "$FILESIZE" -ne "$POOLSIZE" ]; then
        # Output common error messages to the console
        egrep "^(You|Error)" $TEMPFILE
        rm -f $TEMPFILE
        echo_failure
        echo ""
        exit 1
    fi
    cat $TEMPFILE > /dev/urandom
    rm -f $TEMPFILE
    echo_success
    echo ""
    ;;
  stop)
    exit 0
    ;;
  status|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
 *)
    echo "Usage: urandom start|stop" >&2
    exit 3
    ;;
esac
