---
- name: Creating kubernetes cluster
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: create a cluster
    gcp_container_cluster:
      name: "{{KUBERNETES_CLUSTER_NAME}}-{{ ENVIRONMENT }}"
      initial_node_count: "{{ KUBERNETES_CLUSTER_NODE_COUNT }}"
      master_auth:
        username: cluster_admin
        password: my-secret-password
      node_config:
        machine_type: "{{ NODE_MACHINE_TYPE }}"
        disk_size_gb: "{{ DISK_SIZE }}"
        preemptible: "{{ PREEMTIBLE_OPTION }}"
      zone: "{{ GCP_ZONE }}"
#      scopes:
#        - "https://www.googleapis.com/auth/ndev.clouddns.readwrite"
#        - "https://www.googleapis.com/auth/compute"
#        - "https://www.googleapis.com/auth/devstorage.read_only"
#        - "https://www.googleapis.com/auth/logging.write"
#        - "https://www.googleapis.com/auth/monitoring"
#        - "https://www.googleapis.com/auth/servicecontrol"
#        - "https://www.googleapis.com/auth/service.management.readonly"
#        - "https://www.googleapis.com/auth/trace.append"
      project: "{{GCP_PROJECT_NAME}}"
      auth_kind: serviceaccount
      service_account_file: "{{keyfile}}"
      state: present
